### ISSUE TITLE
please add linux binary to the releases

### ISSUE THREAD

**Issue by dasdgw** [andrasdaradici/YoRadio-Theme-Editor#1]
Hi,

nice looking project. But I'm on linux, so I can't use it.
Do you mind also releasing a linux build?
Or maybe add build instructions?
I never built a unity project, so I don't even know where to get started.

**Comment by andrasdaradici** [comment]
Linux binary got added :)

https://github.com/andrasdaradici/YoRadio-Theme-Editor/releases/tag/1.2.0

**Comment by dasdgw** [comment]
Thank you for adding a linux binary!
